[mgr]
show_hidden = true
show_symlink = true
sort_dir_first = true
linemode = "size"

[preview]
wrap = "yes"
tab_size = 2
max_width = 600
max_height = 600
image_delay = 100
image_filter = "catmull-rom"
image_quality = 90

[opener]
vlc_smart = [
    { run = '''
            if pgrep -x "vlc" > /dev/null; then
                vlc --one-instance --playlist-enqueue %s
            else
                setsid vlc --one-instance --loop --playlist-autostart %s >/dev/null 2>&1 &
            fi
        ''', desc = "Queue in VLC" }
]

play_video = [
    { run = 'vlc %s', desc = "Play in VLC", orphan = true }
]

edit_micro = [
    { run = 'micro %s', desc = "Edit with micro", block = true }
]

evince = [
    { run = 'evince %s', desc = "Open default pdf viewer", orphan = true }
]

loupe = [ 
	{ run = 'loupe %s', desc = "Loupe Image Viewer", orphan = true }
]



[open]
rules = [
    # PDF and Audio
    { mime = "application/pdf", use = "evince" },
    { mime = "audio/*", use = [ "vlc_smart", "reveal" ] },
    { url = "*.xspf", use = [ "vlc_smart", "reveal" ] }, # routes vlc-made audio playlists
    
    # Video
    { mime = "video/*", use = "play_video" },

    # Image
    { mime = "image/*", use = "loupe" },

    # Text / Code
    { mime = "{text/*,application/json,application/javascript,application/x-sh}", use = "edit_micro" },
    { name = "*.{toml,conf,yaml,yml,md,txt}", mime = "{text/*,application/json,application/javascript,application/x-sh}", use = "edit_micro" },

    { mime = "inode/empty", use = "edit_micro" },
]

[plugin]
prepend_previewers = [
    { mime = "application/pdf", run = "pdf" },
    { mime = "audio/*", run = "exifaudio" }
]
